### ISSUE TITLE
What should the licence be ?

### ISSUE THREAD

**Issue by lexman** [datasets/world-cities#2]
The recommandations (http://data.okfn.org/doc/publish-faq#-strong-license-strong-) is to licence the data under PDDL and to add a reminder of the original licence of the source.

But @tfmorris noticed that the original data is CC-BY source, which meansthe derivative should be CC-BY as well. I accepted his changes because I tend to agree with him, but does anyone (@rgrp? @pdehaye ? anyone else ?) have an idea of the right licence ?

**Comment by rufuspollock** [comment]
@lexman I would suggest changing to CC-By if that is original source license.

We could also spell this out in README license section saying that original source is CC-By and we are preserving that.

**Comment by lexman** [comment]
So I changed the licence to CC Attribution...
